name: Dart CI

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Flutter
      uses: subosito/flutter-action@v1.1.1
      with:
        channel: beta
    - name: Enable Flutter Web
      run: flutter config --enable-web
    - name: Install dependencies
      run: flutter packages pub get
    - name: Build
      run: flutter build web --release
    - name: Deploy to Zeit
      run: |
        cd build/web
        npx now -n studio -t ${{ secrets.ZEIT_TOKEN }}
